[package]
name = "vtuber_kit"
version = "0.1.0"
authors = ["SCP-EEE <scpeee@wail.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv = "0.46.3"